Add highlight support
subutux/rmapy pull request #22
Opened 2021-05-11 17:31 UTC by sabidib

This adds support for highlights to `ZipDocument` and adds a small entry to the quickstart docs to indicate the highlights folder is there when unzipping.

@subutux for review

2021-05-30 11:45 UTC, subutux requested changes
Thank you for this pull request!

I don't know if this is a remarkable 2 only feature, but I never heard of it and actually don't know how to create an highlight. Is this purely for PDF / EPUB documents?

Could you provide an example zip file from the remarkable cloud containing this highlight file? 

Also, I've added some comments to your merge request, mostly about documentation.

2021-05-30 11:45 UTC, subutux commented on rmapy/document.py
> +
Could you provide some documentation for this class? 
Is this something only supported on the remarkable 2?
Or only in PDF documents?

2021-05-30 11:45 UTC, subutux commented on docs/source/quickstart.rst
Also add some more documentation about highlighting here. Can be a simple sentence like:

> Your highlights are stored in the `{uuid}.highlights/` folder.

Just to provide some clarification.

2021-05-30 11:45 UTC, subutux commented on rmapy/document.py
> +        self.highlight_data = highlight_data
Any reason why you store a `BytesIO` instance instead of converting the JSON to an object?
This could possibly make a developer's live easier to have it already in an object.

2021-07-07 18:14 UTC, sabidib reviewed
Thank you for taking a look at this PR and #21 !

The highlight functionality _should_ be available to both rM1 and rM2 after 2.7, I only have an rM2 myself. It seems to work on EPUBs~, I haven't been able to get it to work on PDFs.~ I was able to get this working on a PDF as well, it depends on the PDF quality.

Simply use the highlight tool to highlight on a section of text and it should snap to it.

Checking the [release page for 2.7](https://support.remarkable.com/hc/en-us/articles/360019414457--Software-release-2-7) I don't see anything indicating that it is rM2 only.

I've opened a [PR here](https://github.com/sabidib/rmapy/pull/1/files) that contains the contents of a zipfile from remarkable cloud with highlights.

Tell me if I've missed anything. Would love to get this merged and a new version published!

2021-07-07 18:55 UTC, sabidib commented
Just found a wrinkle with not treating the highlight as a bytes object, adding another commit shortly...

2021-07-07 20:23 UTC, subutux commented
Hey @sabidib 

Just a quick comment to let you know that you’re awesome! 🚀 

I’ll take a look this weekend and try to merge this ASAP. 

thanks again for your efforts!

2021-07-11 09:37 UTC, merged

2021-07-11 09:37 UTC, subutux commented
:rocket: